import type { Metadata } from "next";
import "./globals.css";
import { Kanit } from "next/font/google";
import Navbar from "@/components/Navbar";

const kanit = Kanit({
  subsets: ["thai", "latin"],
  weight: ["400", "600"],
  variable: "--font-kanit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${kanit.className}`}>
      <body className="pt-20 flex min-h-screen flex-col">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
